### ISSUE TITLE
[DEV] Implement the Chrono-Sphere upgrade feature!

### ISSUE THREAD

**Issue by Vertical-Recoil** [Vertical-Recoil/Galactic-Space-Federation#22]
<h1>Chrono-Sphere upgrade implementation</h2>

Create an upgrade object with the following parameters:

- Upgrade must have its own color box in the game that players can interact with.
- Upgrade must have the same border thickness and color on it as other upgrades.
- Upgrade must have a timer that is represented at the bottom left.
- Timer must be the same color as the upgrade.
- The border of the timer must be the thickness and color of the other timers.

If you are unsure about how to implement the styling of this feature, please refer to the other upgrades.
The logic of the upgrade is as follows:

- [x] The enemy ships get a visual effect while the upgrade is active.
- [x] The upgrade causes enemy ships to slow down by an amount set by some variable.
- [x] Case check the logic to make sure there are no unintentional hiccups, such as bound checking.
- [x] For documentation purposes, title your commits "Game version 1.b.x: 'Commit example'", where b will be determined based on what feature is developed first, @Vertical-Recoil will handle that so call it b for now, x will start at 0 for your base implementation and will increase by 1 for every commit and push that you make to your branch. Instead of 'Commit example', you will write what was done by you in this commit instead.

**_If you have any questions, please reach out to @Vertical-Recoil_** 

<h2>Please comment on this issue if you will be implementing this feature!</h2>

**Comment by AnWings** [comment]
Ill implement this upgrade
