### ISSUE TITLE
[DEV] Implement 2 new enemies, see DESC!

### ISSUE THREAD

**Issue by Vertical-Recoil** [Vertical-Recoil/Galactic-Space-Federation#29]
<h1>Create 2 new enemy types:</h1>

<h3>New Enemy Type 1:</h3>

- [ ] Enemy must have a unique visual representation.
- [ ] Enemy must come into the game after the player reaches MRT difficulty (See code for how the difficulty was implemented via score).
- [ ] Enemy will have a BLUE laser instead of a red one.
- [ ] Taking damage from this enemy will cause the player's movement speed to decrease by 2 (subject to balancing).
- [ ] This enemy's movement speed will be slower than the usual enemy speed. As an example, RGB enemies start slow and get fast with difficulty increase. For this enemy, the speed will remain on the slow side.
- [ ] This enemy takes a little bit longer to spawn than the regular RGB enemies, it is considered a sub-boss.

<h3>New Enemy Type 2:</h3>

- [ ] Enemy must have a unique visual representation.
- [ ] This enemy is a boss, so it will have a bigger health pool (lets go with 5 for now, so you need to shoot him 5 times for it to die)
- [ ] This enemy spawns like all other enemies, but there are 3 caveats. 1, this enemy has a long spawn delay, 2, this enemy only spawns after ERT difficulty is reached, and 3, the boss will move up and down in the direction of the player's y value, and their x value is constrained to the right area of the game. This boss should not be able to pass the player.

<h3>Something to note:</h3>

- For each of these new enemies, since their spawn delay is longer, that means they spawn further to the right offscreen. This also means that they exist in the game and will continue shooting at the player even off the screen. Find a way to incorporate a delay in spawn for these enemies such that they are not able to fire offscreen or their lasers are detoured until the enemy pops up on the screen. The way you implement this is up to you, as long as the desired effect is reached and all cases of bugs are dealt with.
- Please pull the codebase from the main branch before starting to implement this feature in order to reduce errors. This can be done by merging the main branch into your branch here on GitHub and then pulling the data from your branch on GitHub to your local machine by doing 'git pull' while you are in your branch locally.

<h2>Implementation Submission:</h2>

1. Please comment on this issue if you will be working on this feature!
2. Develop the feature in regard to the parameters stated above!
3. For documentation purposes, title your commits "Game version 1.b.x: 'New enemy type implementation example'", where b will be determined based on what feature is developed first, @Vertical-Recoil will handle that so call it b for now, x will start at 0 for your base implementation and will increase by 1 for every commit and push that you make to your branch. Instead of 'New enemy ...', you will write what was done by you in this commit instead.
4. Create a merge request ONLY after the implementation is fully developed, all bugs have been squashed, and a demo was shown to @Vertical-Recoil on discord.

**_If you have any questions, please contact @Vertical-Recoil on Discord!_**

**Comment by ezaypzay** [comment]
Ill work on this
